<?php echo $this->navigation; ?>
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <h3>Test code which handles zend 2 cache api</h3>
            <p>Some configuration based on tutorials on Zend 2 site.</p>
        </div>
        <div class="col-lg-6">
            <h3>Cache with files</h3>
            <p>Using files for storage of data. Slow option.</p>
            <h3>Cache with memcached</h3>
            <p>Using special memory server for storage of data. Very fast.</p>
        </div>
    </div>
</div>
