<?php echo $this->navigation;?>
<div class="row">
    <div class="panel panel-default">
        <div class="panel-body">
            <?php if(isset($error)) :?>
                <p><?php echo "We have a problem: $error";?></p>
            <?php else :?>
                <p><?php echo "Server version:  $version";?></p>
                <p><?php echo "Value of key: $result";?></p>
                <p><?php echo "Does cache had the key: $success";?></p>
            <?php endif; ?>
        </div>
    </div>
</div>
