<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/jquery.sliphover.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>
<body>
<div id="wrap">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img
                        src="<?php echo $this->basePath('img/zf2-logo.png') ?>"
                        alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('TestingZend2') ?></a>
            </div>
            <p class="text-center topic">
                <?php $this->navigation()->menu()->setPartial('application/partials/menu');
                echo $this->navigation('main-navigation')->menu();
                ?>
            </p>
        </div>
    </nav>
    <div class="container">
        <?php echo $this->content; ?>
    </div>
    <!-- /container -->
</div>
<footer id="footer" class="container">
    <p>Project which testing different custom modules.</p>
</footer>
<?php echo $this->inlineScript() ?>
</body>
</html>
