<div class="row">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="nav-pic" id="pictures-slides">
                <ul>
                    <li>
                        <a href="<?php echo $this->url('cache') ?>">
                            <img src="<?php echo $this->basePath() . '/img/cache.png' ?>" title="Custom cache code">
                        </a>
                    </li>
                    <li>

                        <a>
                            <img src="<?php echo $this->basePath() . '/img/love_coding.jpeg'?>">
                        </a>
                    </li>
                    <li>

                        <a>
                            <img src="<?php echo $this->basePath() . '/img/authentication.jpg' ?>">
                        </a>
                    </li>
                    <li>
                        <a>
                            <img src="<?php echo $this->basePath() . '/img/memcached.jpg' ?>">
                        </a>
                    </li>
                    <li>

                        <a>
                            <img src="<?php echo $this->basePath() . '/img/navigation.jpg'?>">
                        </a>
                    </li>
                    <li>

                        <a>
                            <img src="<?php echo $this->basePath() . '/img/love_coding.jpeg'?>">
                        </a>
                    </li>
                    <li>
                        <a>
                            <img src="<?php echo $this->basePath() . '/img/memcached.jpg' ?>">
                        </a>
                    </li>
                    <li>

                        <a>
                            <img src="<?php echo $this->basePath() . '/img/authentication.jpg' ?>">

                        </a>
                    </li>
                    <li>

                        <a>
                            <img src="<?php echo $this->basePath() . '/img/authentication.jpg' ?>">
                        </a>
                    </li>
                    <li>
                        <a>
                            <img src="<?php echo $this->basePath() . '/img/memcached.jpg' ?>">
                        </a>
                    </li>
                    <li>

                        <a>
                            <img src="<?php echo $this->basePath() . '/img/love_coding.jpeg'?>">
                        </a>
                    </li>
                    <li>

                        <a>
                            <img src="<?php echo $this->basePath() . '/img/navigation.jpg'?>">
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php $this->inlineScript()->captureStart();
echo<<<JS
    $('#pictures-slides').sliphover();
JS;
$this->inlineScript()->captureEnd();
?>